name: Docs2Pages
on:
  push:
    tags: '*'
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: install sphinx
      run: pip install -U sphinx
    - uses: abatilo/actions-poetry@v2.1.3
    - name: install
      run: poetry install -E dev
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        make html
        cp -r build/html gh-pages/        
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
